/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DAO.AdiantamentosDAO;
import model.DAO.FuncionariosDAO;
import model.bean.Adiantamentos;
import model.bean.Funcionarios;

/**
 *
 * @author Sadrac
 */
public class ViewFuncionario extends javax.swing.JFrame {
 
    /**
     * Creates new form ViewFuncionario
     */
    public ViewFuncionario() {
        initComponents();
        panUpdate.setVisible(false);
        jPanel1.setVisible(false);
    }
    
  
    public int getFormJFrame(int id){
        
        lblID.setText(Integer.toString(id));
        
        read("",Integer.parseInt(lblID.getText()));
        return id;
    }
   
    public void read(String string,int idFuncionario){
         DefaultTableModel formatarTable = (DefaultTableModel) tableAdiantamento.getModel();
        // Reseta a tabela
        formatarTable.setNumRows(0);
        AdiantamentosDAO aDAO = new AdiantamentosDAO();
        Funcionarios f = new Funcionarios();
        f.setId(Integer.parseInt(lblID.getText()));
        
        
        float soma = 0;
        for(Adiantamentos a: aDAO.read(f)){
            String dia = a.getDataAdiantamento().substring(8,10);
            String mes = a.getDataAdiantamento().substring(5,7);
            String ano = a.getDataAdiantamento().substring(0,4);
            String dataAdiantamento = dia+"/"+mes+"/"+ano;
            
            Object[] linhas = {
               a.getId(),
               dataAdiantamento,
               a.getSalAdiantado()
            };
            
           formatarTable.addRow(linhas);
           soma+=a.getSalAdiantado();
        }
        lblTotal.setText(Float.toString(soma));
        
    }
    public void read(int id){
        FuncionariosDAO fDAO = new FuncionariosDAO();
        
           for(Funcionarios f: fDAO.readForUpdate(id)){
               
              Date data = new Date();
              DateFormat dataFormatada = new SimpleDateFormat("Y");
              int anoAtual = Integer.parseInt(dataFormatada.format(data));
              txtNome.setText(f.getNome());
              txtObra.setText(f.getObra());
              String dia = f.getDatanascimento().substring(8,10);
              String mes = f.getDatanascimento().substring(5,7);
              String ano = f.getDatanascimento().substring(0,4);
              txtDataNasc.setText(dia+"/"+mes+"/"+ano);
              int anoNasc = Integer.parseInt(ano);
              int idade = anoAtual - anoNasc;
              lblIdade.setText(Integer.toString(idade));
               
           }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableAdiantamento = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnLimparMes = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        txtDataNasc = new javax.swing.JTextField();
        txtDataAdiant = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtObra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnCriar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        panUpdate = new javax.swing.JPanel();
        btnAdiantExcluir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblAdiantID = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableAdiantamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Dia do Adiantamento", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableAdiantamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAdiantamentoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableAdiantamento);

        jLabel1.setText("TOTAL:");

        lblTotal.setText("0");

        btnLimparMes.setText("Limpar mês");
        btnLimparMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparMesActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome:");

        jLabel4.setText("Idade no final do ano:");

        lblIdade.setText("0");

        jLabel6.setText("Data de nascimento:");

        jLabel7.setText("Obra:");

        jLabel8.setText("Data de adiantamento:");

        jLabel9.setText("Valor:");

        btnCriar.setText("Criar");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jLabel2.setText("ID:");

        lblID.setText("0");

        btnExcluir.setBackground(new java.awt.Color(255, 0, 0));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAdiantExcluir.setBackground(new java.awt.Color(255, 0, 0));
        btnAdiantExcluir.setText("Excluir");
        btnAdiantExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdiantExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panUpdateLayout = new javax.swing.GroupLayout(panUpdate);
        panUpdate.setLayout(panUpdateLayout);
        panUpdateLayout.setHorizontalGroup(
            panUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panUpdateLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(btnAdiantExcluir)
                .addContainerGap())
        );
        panUpdateLayout.setVerticalGroup(
            panUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panUpdateLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnAdiantExcluir)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        lblAdiantID.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblAdiantID)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblAdiantID)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblIdade)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtObra, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 993, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCriar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(13, 13, 13)
                                .addComponent(txtDataAdiant, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLimparMes)
                        .addGap(35, 35, 35)
                        .addComponent(btnVoltar)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(lblTotal)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnExcluir)
                        .addGap(31, 31, 31)
                        .addComponent(btnAtualizar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(204, 204, 204)
                        .addComponent(panUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(lblIdade)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(txtObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(lblID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtualizar)
                    .addComponent(btnExcluir))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataAdiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCriar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(panUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblTotal)
                            .addComponent(btnLimparMes)
                            .addComponent(btnVoltar))
                        .addGap(70, 70, 70))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
       // System.out.println(lblID.getText());
        this.dispose();
        ViewAdiantSalarial vas = new ViewAdiantSalarial();
        vas.show(true);
        
        
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        FuncionariosDAO fDAO = new FuncionariosDAO();
        Funcionarios f = new Funcionarios();
        
        String dia = txtDataNasc.getText().substring(0,2);
        String mes = txtDataNasc.getText().substring(3,5);
        String ano = txtDataNasc.getText().substring(6);
        
        f.setDatanascimento(ano+"-"+mes+"-"+dia);
        f.setNome(txtNome.getText());
        f.setObra(txtObra.getText());
        f.setId(Integer.parseInt(lblID.getText()));
        fDAO.update(f);
        this.dispose();
        ViewAdiantSalarial vas = new ViewAdiantSalarial();
        vas.show(true);
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        
        FuncionariosDAO fDAO = new FuncionariosDAO();
        Funcionarios f = new Funcionarios();
        f.setId(Integer.parseInt(lblID.getText()));
        
        fDAO.delete(f);
        this.dispose();
        ViewAdiantSalarial vas = new ViewAdiantSalarial();
        vas.show(true);
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        // TODO add your handling code here:
        
        Adiantamentos a = new Adiantamentos();
        AdiantamentosDAO aDAO = new AdiantamentosDAO();
        
        String dia = txtDataAdiant.getText().substring(0,2);
        String mes = txtDataAdiant.getText().substring(3,5);
        String ano = txtDataAdiant.getText().substring(6);
        a.setDataAdiantamento(ano+"-"+mes+"-"+dia);
        a.setSalAdiantado(Float.parseFloat(txtValor.getText()));
        a.setIdfuncionario(Integer.parseInt(lblID.getText()));
        
        aDAO.create(a);
        read("",Integer.parseInt(lblID.getText()));
        
        txtDataAdiant.setText("");
        txtValor.setText("");
    }//GEN-LAST:event_btnCriarActionPerformed

    private void btnLimparMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparMesActionPerformed
        // TODO add your handling code here:
        
        Adiantamentos a = new Adiantamentos();
        AdiantamentosDAO aDAO = new AdiantamentosDAO();
        
        a.setIdfuncionario(Integer.parseInt(lblID.getText()));
        aDAO.delete(a);
        read("",Integer.parseInt(lblID.getText()));
        
        txtDataAdiant.setText("");
        txtValor.setText("");
    }//GEN-LAST:event_btnLimparMesActionPerformed

    private void tableAdiantamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAdiantamentoMouseClicked
        // TODO add your handling code here:
        
        int linhaSelecionada = tableAdiantamento.getSelectedRow();
       
        
        if(linhaSelecionada >= 0){
            panUpdate.setVisible(true);
            lblAdiantID.setText(tableAdiantamento.getValueAt(linhaSelecionada, 0).toString());
          
        }else{
            JOptionPane.showMessageDialog(null, "Você não selecionou nenhuma linha");
        }
        
    }//GEN-LAST:event_tableAdiantamentoMouseClicked

    private void btnAdiantExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdiantExcluirActionPerformed
        // TODO add your handling code here:
         panUpdate.setVisible(false);
         AdiantamentosDAO aDAO = new AdiantamentosDAO();
         aDAO.delete(Integer.parseInt(lblAdiantID.getText()));
         read("",Integer.parseInt(lblID.getText()));
        
        txtDataAdiant.setText("");
        txtValor.setText("");
    }//GEN-LAST:event_btnAdiantExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewFuncionario().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdiantExcluir;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimparMes;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAdiantID;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panUpdate;
    private javax.swing.JTable tableAdiantamento;
    private javax.swing.JTextField txtDataAdiant;
    private javax.swing.JTextField txtDataNasc;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtObra;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
